### ISSUE TITLE
error when changing to another db

### ISSUE THREAD

**Issue by gfernandez-me** [hakimLyon/epic-stack-with-prisma-mongodb#2]
![image](https://github.com/hakimLyon/epic-stack-with-prisma-mongodb/assets/5313969/f1fd10e4-7f3c-4b3a-ab50-5af0d0bd0414)

**Comment by hakimLyon** [comment]
This is configured only to use MongoDB as the database.
You can switch to SQLite, but it will require several modifications. 
If you want to use SQLite as the database, one solution is to initialize a new project with the following command: 

`npx create-epic-app@latest`

[Epic Stack app](https://github.com/epicweb-dev/epic-stack)
